
APP_MAP_DIR=$(shell pwd)

APP_MAP_1905DAEMON_DIR=$(APP_MAP_DIR)/1905daemon
APP_MAP_LIBMAPD_DIR=$(APP_MAP_DIR)/libmapd
APP_MAP_HAL_MAP_DIR=$(APP_MAP_DIR)/hal_map
APP_MAP_MAPD_DIR=$(APP_MAP_DIR)/mapd

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
LIB_INSTALL_DIR:=$(APP_MAP_DIR)/map_r2_lib
FILESYSTEM_DIR:=$(APP_MAP_DIR)/map_r2_fs

LIBINSTALL_CFLAGS=
LIBINSTALL_CFLAGS+= -I$(LIB_INSTALL_DIR)
export LIBINSTALL_CFLAGS

LIBINSTALL_LDFLAGS=
endif