
/***************************************************************
Copyright Statement:

This software/firmware and related documentation (EcoNet Software) 
are protected under relevant copyright laws. The information contained herein 
is confidential and proprietary to EcoNet (HK) Limited (EcoNet) and/or 
its licensors. Without the prior written permission of EcoNet and/or its licensors, 
any reproduction, modification, use or disclosure of EcoNet Software, and 
information contained herein, in whole or in part, shall be strictly prohibited.

EcoNet (HK) Limited  EcoNet. ALL RIGHTS RESERVED.

BY OPENING OR USING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY 
ACKNOWLEDGES AND AGREES THAT THE SOFTWARE/FIRMWARE AND ITS 
DOCUMENTATIONS (ECONET SOFTWARE) RECEIVED FROM ECONET 
AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON AN AS IS 
BASIS ONLY. ECONET EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, 
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, 
OR NON-INFRINGEMENT. NOR DOES ECONET PROVIDE ANY WARRANTY 
WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTIES WHICH 
MAY BE USED BY, INCORPORATED IN, OR SUPPLIED WITH THE ECONET SOFTWARE. 
RECEIVER AGREES TO LOOK ONLY TO SUCH THIRD PARTIES FOR ANY AND ALL 
WARRANTY CLAIMS RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES 
THAT IT IS RECEIVERS SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD 
PARTY ALL PROPER LICENSES CONTAINED IN ECONET SOFTWARE.

ECONET SHALL NOT BE RESPONSIBLE FOR ANY ECONET SOFTWARE RELEASES 
MADE TO RECEIVERS SPECIFICATION OR CONFORMING TO A PARTICULAR 
STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND 
ECONET'S ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE ECONET 
SOFTWARE RELEASED HEREUNDER SHALL BE, AT ECONET'S SOLE OPTION, TO 
REVISE OR REPLACE THE ECONET SOFTWARE AT ISSUE OR REFUND ANY SOFTWARE 
LICENSE FEES OR SERVICE CHARGES PAID BY RECEIVER TO ECONET FOR SUCH 
ECONET SOFTWARE.
***************************************************************/

#ifndef __SVC_CFG_TYPE_H__
#define __SVC_CFG_TYPE_H__

#include <common/ecnt_global_macro.h>


#define 	CFG_TYPE_BASE_VAL			100
#define 	CFG_TYPE_MAX_NUM			1000

#define 	CFG_TYPE_FLAG_MULTIPLE		(1<<8)
#define 	CFG_TYPE_FLAG_MEMORY		(1<<9)
#define		CFG_TYPE_FLAG_UPDATE		(1<<10)


#define		CFG_TYPE_MAX_LAN_ENTRY_NUM				1
#define		CFG_TYPE_MAX_WAN_PVC_NUM				8
#define		CFG_TYPE_MAX_WAN_ENTRY_NUM				8
#define		CFG_TYPE_MAX_WANINFO_ENTRY_NUM			64
#define		CFG_TYPE_MAX_DHCPD_ENTRY_NUM			8
#define		CFG_TYPE_MAX_DHCPLEASE_ENTRY_NUM		254
#define		CFG_TYPE_MAX_LANHOST_ENTRY_NUM			254
#define		CFG_TYPE_MAX_WLAN_ENTRY_NUM				16
#define		CFG_TYPE_MAX_ROUTE_ENTRY_NUM			64
#define		CFG_TYPE_MAX_ROUTE6_ENTRY_NUM			16
#define		CFG_TYPE_MAX_NAT_PVC_NUM				8
#define		CFG_TYPE_MAX_DMZ_ENTRY_NUM				64
#define		CFG_TYPE_MAX_VIRSERVER_ENTRY_NUM		64
#define		CFG_TYPE_MAX_DDNS_ENTRY_NUM				64
#define		CFG_TYPE_MAX_SWITCHPARA_ENTRY_NUM		4
#define		CFG_TYPE_MAX_ACCOUNT_ENTRY_NUM			3
#define		CFG_TYPE_MAX_DIAGNOSTIC_PVC_NUM			CFG_TYPE_MAX_WAN_PVC_NUM
#define		CFG_TYPE_MAX_DEVICEINFO_PVC_NUM			CFG_TYPE_MAX_WAN_PVC_NUM
#define		CFG_TYPE_MAX_QOS_ENTRY_NUM				30
#define		CFG_TYPE_MAX_VLANBIND_ENTRY_NUM			10
#define		CFG_TYPE_MAX_ACL_ENTRY_NUM				16
#define		CFG_TYPE_MAX_URLFILTER_ENTRY_NUM		100
#define		CFG_TYPE_MAX_AUTOPVC_ENTRY_NUM			16
#define		CFG_TYPE_MAX_SSLCA_ENTRY_NUM			4
#define		CFG_TYPE_MAX_ACCESSLIMIT_ENTRY_NUM		4
#define		CFG_TYPE_MAX_CTDIAGNOSTIC_ENTRY_NUM		3
#define		CFG_TYPE_MAX_DEVICEALARM_ENTRY_NUM			10
#define		CFG_TYPE_MAX_DEVICEMONITOR_ENTRY_NUM		10
#define		CFG_TYPE_MAX_APPFTP_ENTRY_NUM				10
#define		CFG_TYPE_MAX_PLUGIN_ENTRY_NUM				100
#define		CFG_TYPE_MAX_USBMOUNT_ENTRY_NUM				3
#define		CFG_TYPE_MAX_UPNPDMSWPROFILE_ENTRY_NUM		4
#define		CFG_TYPE_MAX_UPNPDMSERVICE_ENTRY_NUM		4
#define		CFG_TYPE_MAX_UPNPDMAPINT_ENTRY_NUM				4
#define		CFG_TYPE_MAX_UPNPDMAPIPTV_ENTRY_NUM				4
#define		CFG_TYPE_MAX_STORAGEACCESSRIGHT_ENTRY_NUM		64
#define		CFG_TYPE_MAX_ATTACHWANDNSTUNNEL_PVC_NUM			8
#define		CFG_TYPE_MAX_LANINFO_ENTRY_NUM					64
#define		CFG_TYPE_MAX_DNSSPEEDLIMIT_ENTRY_NUM			16
#define		CFG_TYPE_MAX_BANDWIDTH_ENTRY_NUM				30
#define		CFG_TYPE_MAX_MAXBANDWIDTH_ENTRY_NUM				10
#define		CFG_TYPE_MAX_LANHOST2_ENTRY_NUM					MAX_LANHOST2_ENTRY_NUM

#ifdef VOIP_MAX_CHAN
#define		CFG_TYPE_MAX_VOIP_LINE_NUM               VOIP_MAX_CHAN   /* VOIP_MAX_CHAN */
#else
#define		CFG_TYPE_MAX_VOIP_LINE_NUM               4   /* VOIP_MAX_CHAN */
#endif
#define		CFG_TYPE_VOIP_SIMULATE_LINE_NUM          CFG_TYPE_MAX_VOIP_LINE_NUM
#define		CFG_TYPE_VOIP_MAX_CODEC_NUM						10
#define		CFG_TYPE_VOIP_PHONE_BOOK_NUM					10
#define		CFG_TYPE_VOIP_INFO_NUM                   CFG_TYPE_MAX_VOIP_LINE_NUM
#define		CFG_TYPE_VOIP_POOR_QL_NUM						10
#define		CFG_TYPE_EVENTNUM_RULE							4
#if defined(TCSUPPORT_CT_JOYME4)
#define		CFG_TYPE_MAX_IPMACFILTER_ENTRY_NUM		180
#else
#define		CFG_TYPE_MAX_IPMACFILTER_ENTRY_NUM		240
#endif

#define		CFG_TYPE_MAX_DHCPV6_SERVER_NUM					64
#define		CFG_TYPE_MAX_RADVD_NUM						64
#endif
