
/***************************************************************
Copyright Statement:

This software/firmware and related documentation (EcoNet Software) 
are protected under relevant copyright laws. The information contained herein 
is confidential and proprietary to EcoNet (HK) Limited (EcoNet) and/or 
its licensors. Without the prior written permission of EcoNet and/or its licensors, 
any reproduction, modification, use or disclosure of EcoNet Software, and 
information contained herein, in whole or in part, shall be strictly prohibited.

EcoNet (HK) Limited  EcoNet. ALL RIGHTS RESERVED.

BY OPENING OR USING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY 
ACKNOWLEDGES AND AGREES THAT THE SOFTWARE/FIRMWARE AND ITS 
DOCUMENTATIONS (ECONET SOFTWARE) RECEIVED FROM ECONET 
AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON AN AS IS 
BASIS ONLY. ECONET EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, 
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, 
OR NON-INFRINGEMENT. NOR DOES ECONET PROVIDE ANY WARRANTY 
WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTIES WHICH 
MAY BE USED BY, INCORPORATED IN, OR SUPPLIED WITH THE ECONET SOFTWARE. 
RECEIVER AGREES TO LOOK ONLY TO SUCH THIRD PARTIES FOR ANY AND ALL 
WARRANTY CLAIMS RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES 
THAT IT IS RECEIVERS SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD 
PARTY ALL PROPER LICENSES CONTAINED IN ECONET SOFTWARE.

ECONET SHALL NOT BE RESPONSIBLE FOR ANY ECONET SOFTWARE RELEASES 
MADE TO RECEIVERS SPECIFICATION OR CONFORMING TO A PARTICULAR 
STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND 
ECONET'S ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE ECONET 
SOFTWARE RELEASED HEREUNDER SHALL BE, AT ECONET'S SOLE OPTION, TO 
REVISE OR REPLACE THE ECONET SOFTWARE AT ISSUE OR REFUND ANY SOFTWARE 
LICENSE FEES OR SERVICE CHARGES PAID BY RECEIVER TO ECONET FOR SUCH 
ECONET SOFTWARE.
***************************************************************/


#ifndef __SVC_PON_SVC_H__
#define __SVC_PON_SVC_H__


#define PON_CFG_PARENT_NODE_LENTH   8
#define PON_CFG_MAX_NODE_LENTH      32
#define PON_CFG_MAX_ATTR_LENTH      32
#define PON_CFG_MAX_ATTR_VAL_LENTH  128

#define SVC_PON_CFG_TYPE_XPON		(0)
#define SVC_PON_CFG_TYPE_GPON		(1)
#define SVC_PON_CFG_TYPE_OMCI		(2)
#define SVC_PON_CFG_TYPE_EPON		(3)
#define SVC_PON_CFG_TYPE_OAM		(4)

typedef enum
{
	XPON_CHILD_COMMON,
    XPON_CHILD_LINKCFG
}xpon_child_node_t;

typedef enum
{
	GPON_CHILD_COMMON,
    GPON_CHILD_ONU,
    GPON_CHILD_ANI,
    GPON_CHILD_OLT,
    GPON_CHILD_SOFTIMAGE_0,
    GPON_CHILD_SOFTIMAGE_1,
    GPON_CHILD_CAPABILITY,
    GPON_CHILD_LOIDAUTH,
    GPON_CHILD_GEMPORT
}gpon_child_node_t;


typedef enum
{
	EPON_CHILD_ONU,
    EPON_CHILD_PON,
    EPON_CHILD_POWERSAVING,
    EPON_CHILD_LOIDAUTH,
    EPON_CHILD_SOFTIMAGE,
    EPON_CHILD_SERVICESLA
}epon_child_node_t;

typedef enum
{
	OMCI_CHILD_ENTRY
}omci_child_node_t;

typedef enum
{
	OAM_CHILD_ENTRY,
	OAM_CHILD_CTC,
	OAM_CHILD_CUC
}oam_child_node_t;

typedef struct pon_cfg_update_event {
	unsigned char 	parent;
	unsigned char 	child;
    char 			attr[PON_CFG_MAX_ATTR_LENTH];
    char 			val[PON_CFG_MAX_ATTR_VAL_LENTH];
}pon_cfg_update_t;

typedef enum evt_pon_id{
	CFG_PON_SET = 1,
	CFG_PON_COMMIT = 2
}evt_pon_id_t;

#endif

