#!/bin/sh
PROFILE_CFG=/userfs/profile.cfg
if [ -f $PROFILE_CFG ] ; then
    chmod 777 $PROFILE_CFG
    . $PROFILE_CFG
fi

if [ "$TCSUPPORT_AUTOBENCH" != "" ] ;then
	echo "execute rcS_AutoBench"
	chmod 777 /usr/etc/init.d/rcS_AutoBench
	/usr/etc/init.d/rcS_AutoBench
	exit 0
fi

if [ "$TCSUPPORT_2_6_36_KERNEL" != "" ] ;then
	KERNEL_DIR=/lib/modules/2.6.36
else
	KERNEL_DIR=/lib/modules/2.6.22.15
fi
mount -a

# frank added 20110128
if [ "$TCSUPPORT_SDRAM_16M" != "" ] ;then
/userfs/bin/skbmgr 1280 400 &
fi

/bin/busybox cp -a /usr/etc /tmp

/bin/mkdir -m 0777 -p /tmp/var
/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/tmp

if [  "$TCSUPPORT_CPU_RT63365" != "" ] && [ "$TCSUPPORT_POWERSAVE_ENABLE" != ""  ] ;then
insmod /lib/modules/pwm.ko
fi
if [ "$TCSUPPORT_RESTORE_LINOS_INFO" != "" ] ;then
	echo "do restore linos info"
	/userfs/bin/restore_linos_info
fi

if [ "$TCSUPPORT_2_6_36_KERNEL" = "" ] ;then
insmod /lib/modules/tcfullcone.ko
fi
insmod /lib/modules/module_sel.ko
if [  "$TCSUPPORT_CPU_RT65168" != "" ] ;then
insmod /lib/modules/pwm.ko
fi
if [ "$TCSUPPORT_SMUX" != "" ] ;then
insmod /lib/modules/multiwan.ko
fi

if [ "$TCSUPPORT_FTP_THROUGHPUT" != "" ] ;then
echo "Not insmod portbind and(or) vlantag modules!"
else
if [ "$TCSUPPORT_PORTBIND" != "" ] ;then
insmod /lib/modules/tcportbind.ko
fi
if [ "$TCSUPPORT_VLAN_TAG" != "" ] ;then
insmod /lib/modules/tcvlantag.ko
fi
fi

if [ "$TCSUPPORT_BRIDGE_FASTPATH" != "" ] ;then
insmod /lib/modules/brg_shortcut.ko
fi

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
if [ "$TCSUPPORT_CWMP_FAST_GET" != "" ] ;then
echo 4096 > /proc/sys/net/nf_conntrack_max
else
echo 2048 > /proc/sys/net/nf_conntrack_max
fi

if [ "$TCSUPPORT_NAT_SESSION_RESERVE" != "" ] ;then
if [ "$TCSUPPORT_CWMP_FAST_GET" != "" ] ;then
echo 2048 > /proc/sys/net/netfilter/nf_conntrack_reserve
else
echo 500 > /proc/sys/net/netfilter/nf_conntrack_reserve
fi
# 6: TCP  17:UDP  
echo 6 > /proc/sys/net/netfilter/nf_conntrack_reserve_proto
echo 80 > /proc/sys/net/netfilter/nf_conntrack_reserve_port
fi

if [ "$TCSUPPORT_IPV6" != "" ] ;then
echo "TCSUPPORT_IPV6"
#Modify gc_stale_time for IPv6 self test
echo 6000 > /proc/sys/net/ipv6/neigh/default/gc_stale_time

echo 1 >/proc/sys/net/ipv6/conf/all/forwarding
fi

#krammer add for LAN can't continuous ping to WAN when exchenging the routing mode
#bug1126
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout 

echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route


insmod /lib/modules/tcledctrl.ko
insmod /lib/modules/tccicmd.ko

if [ "$TCSUPPORT_FON" != "" ] ;then
insmod $KERNEL_DIR/kernel/drivers/net/tun.ko
if [ "$TCSUPPORT_FON_MODEL_B" != "" ] || [ "TCSUPPORT_FON_MODEL_A" != "" ] ;then
insmod $KERNEL_DIR/kernel/net/sched/sch_tbf.ko
fi
elif [ "$TCSUPPORT_FON_V2" != "" ] ;then
insmod $KERNEL_DIR/kernel/net/sched/sch_hfsc.ko
insmod $KERNEL_DIR/kernel/net/sched/act_connmark.ko
insmod $KERNEL_DIR/kernel/net/sched/sch_ingress.ko
insmod $KERNEL_DIR/kernel/net/sched/cls_basic.ko
if [ "$TCSUPPORT_QOS" = "" ] ;then
insmod $KERNEL_DIR/kernel/net/sched/cls_fw.ko
fi
insmod $KERNEL_DIR/kernel/net/netfilter/xt_connbytes.ko
insmod $KERNEL_DIR/kernel/net/netfilter/xt_length.ko
#insmod $KERNEL_DIR/kernel/net/netfilter/xt_mark.ko
if [ "$TCSUPPORT_2_6_36_KERNEL" != "" ] ;then
#No test for kernel_2_6_36, just for reference
insmod $KERNEL_DIR/kernel/net/netfilter/xt_connmark.ko
insmod $KERNEL_DIR/kernel/net/netfilter/xt_recent.ko
insmod $KERNEL_DIR/kernel/net/netfilter/nf_tproxy_core.ko
insmod $KERNEL_DIR/kernel/net/netfilter/xt_TPROXY.ko
else
#insmod $KERNEL_DIR/kernel/net/netfilter/xt_CONNMARK.ko
insmod $KERNEL_DIR/kernel/net/netfilter/xt_CONNMARK_target.ko
insmod $KERNEL_DIR/kernel/net/ipv4/netfilter/ipt_recent.ko
insmod $KERNEL_DIR/kernel/net/ipv4/netfilter/ipt_REDIRECT.ko
fi
insmod $KERNEL_DIR/kernel/net/ipv4/netfilter/ipt_REJECT.ko
#Can use imq instead
insmod $KERNEL_DIR/kernel/drivers/net/ifb.ko
ifconfig ifb0 up
ifconfig ifb1 up
fi

/userfs/bin/cfg_manager & 
sleep 2

#LED GPIO Settings
CONFFILE=/etc/led.conf
if [ -f $CONFFILE ]; then
	chmod 777 $CONFFILE
	. $CONFFILE
fi
if [ "$LAN" != "" ]; then
	echo $LAN > /proc/tc3162/led_def
fi



if [ "$TCSUPPORT_HW_CRYPTO" != "" ] ;then
# insmod crypto_k.ko before any wan interface modules are loaded,
# otherise, pcaket may go into kernel ipsec before crypto_k
# registers ipsec function pointers to Kernel which will
# cause system crash!
insmod /lib/modules/crypto_k.ko
fi

if [ "$TCSUPPORT_CPU_TC3162" != "" ] ;then
echo "insmod tc3162 mac driver" 
insmod /lib/modules/tc3162l2mac.ko
fi

if [ "$TCSUPPORT_CPU_TC3162U" != "" -o "$TCSUPPORT_CPU_RT63260" != "" ] ;then
echo "insmod tc3162u mac driver" 
insmod /lib/modules/tc3162l2mac.ko
fi

if [ "$TCSUPPORT_CPU_TC3262" != "" ] ;then
echo "insmod tc3262 gmac driver"
insmod /lib/modules/tc3262gmac.ko
fi

if [ "$TCSUPPORT_CPU_TC3182" != ""  -o "$TCSUPPORT_CPU_RT63165" != "" -o "$TCSUPPORT_CPU_RT65168" != "" ] ;then
echo "insmod tc3262 gmac driver"
insmod /lib/modules/tc3262gmac.ko
if [ "$TCSUPPORT_CPU_RT65168" != "" ] && [ "$TCSUPPORT_VOIP" = "" ];then
echo 8 >/proc/irq/22/smp_affinity
fi
if [ -f "/proc/tc3162/sys_has_2gmac" ] ;then
if [ "$TCSUPPORT_WAN_ETHER" != "" ] ;then
insmod /lib/modules/tc3262gmac1.ko
echo 2 > /proc/irq/16/smp_affinity
fi
fi	
if [ -f "/proc/tc3162/sys_has_ptm" ] ;then
if [ "$TCSUPPORT_WAN_PTM" != "" ] ;then
insmod /lib/modules/tc3262ptm.ko
fi
fi	
if [ -f "/proc/tc3162/sys_has_hwnat" ] ;then
if [ "$TCSUPPORT_HWNAT" != "" ] ;then
insmod /lib/modules/hwnat.ko
fi
fi	
fi

if [ "$TCSUPPORT_CPU_RT63365" != "" ] || [ "$TCSUPPORT_CPU_RT63368" != "" ] ;then
echo "insmod raeth driver"
insmod /lib/modules/raeth.ko
if [ "$TCSUPPORT_VOIP" = "" ];then
echo 8 >/proc/irq/22/smp_affinity
fi
fi

if [ "$TCSUPPORT_WAN_ATM" != "" ] ;then
insmod /lib/modules/tc3162l2sar.ko
if [ "$TCSUPPORT_CPU_TC3182" != ""  -o "$TCSUPPORT_CPU_RT63365" != ""  -o "$TCSUPPORT_CPU_RT63368" != ""  -o "$TCSUPPORT_CPU_RT65168" != "" ] ;then
#Binding sar to VPE 2. shnwind add.
echo 4 >/proc/irq/23/smp_affinity
fi
elif [ ! "$TCSUPPORT_WAN_PTM" != "" -a ! "$TCSUPPORT_WAN_ETHER" != "" ] ;then
insmod /lib/modules/tc3162l2sar.ko
fi
insmod /lib/modules/tc3162_dmt.ko

if [ "$TCSUPPORT_WLAN" != "" ] && [ -f "/proc/tc3162/sys_has_wifi" ] ;then
echo "TCSUPPORT_WLAN"
if [ "$TCSUPPORT_WLAN_RT2561" != "" ] ;then
echo "TCSUPPORT_WLAN_RT2561"
insmod /lib/modules/rt61ap.ko
fi
if [ "$TCSUPPORT_WLAN_RT3390" != "" ] ;then
echo "TCSUPPORT_WLAN_RT3390"
insmod /lib/modules/rt3390ap.ko
fi
if [ "$TCSUPPORT_WLAN_RT5392" != "" ] ;then
echo "TCSUPPORT_WLAN_RT5392"
insmod /lib/modules/rt5390ap.ko
fi
if [ "$TCSUPPORT_WLAN_RT5390" != "" ] ;then
echo "TCSUPPORT_WLAN_RT5390"
insmod /lib/modules/rt5390ap.ko
fi
if [ "$TCSUPPORT_WLAN_RT5390HL" != "" ] ;then
echo "TCSUPPORT_WLAN_RT5390HL"
insmod /lib/modules/rt5390ap.ko
fi
if [ "$TCSUPPORT_WLAN_MT7601E" != "" ] ;then
echo "TCSUPPORT_WLAN_MT7601E"
insmod /lib/modules/mt7601Eap.ko
fi
if [ "$TCSUPPORT_WLAN_RT3090" != "" ] ;then
echo "TCSUPPORT_WLAN_RT3090"
insmod /lib/modules/rt3090ap.ko
fi
if [ "$TCSUPPORT_DUAL_WLAN_RT5592" != "" ] ;then
echo "TCSUPPORT_DUAL_WLAN_RT5592"
insmod /lib/modules/rt5592ap.ko
fi
if [ "$TCSUPPORT_DUAL_WLAN_RT3593" != "" ] ;then
echo "TCSUPPORT_DUAL_WLAN_RT3593"
insmod /lib/modules/rt3593ap.ko
fi
if [ "$TCSUPPORT_WLAN_MULTIDRIVER" != "" ] ;then
echo "TCSUPPORT_WLAN_MULTIDRIVER"
insmod /lib/modules/rt3593ap.ko
fi
if [ "$TCSUPPORT_DUAL_WLAN_MT7610E" != "" ] ;then
echo "TCSUPPORT_DUAL_WLAN_MT7610E"
insmod /lib/modules/mt7610e_ap.ko
fi
fi



#if [ "$TCSUPPORT_CPU_RT63368" != ""  -o "$TCSUPPORT_CPU_RT63365" != "" ] && [ "$TCSUPPORT_ENDURANCE_WDOG" != ""  -o "$TCSUPPORT_CZ_GENERAL" != "" ] ;then
if [ "$TCSUPPORT_CPU_TC3182" != ""  -o "$TCSUPPORT_CPU_RT63365" != "" -o "$TCSUPPORT_CPU_RT65168" != "" -o "$TCSUPPORT_CPU_RT63368" != "" ] ;then
echo 4 > /proc/irq/25/smp_affinity
fi

# support QoS
if [ "$TCSUPPORT_FTP_THROUGHPUT" != "" ] ;then
echo "Not insmod qos modules!"
else
if [ "$TCSUPPORT_QOS" != "" ] ;then
insmod $KERNEL_DIR/kernel/net/sched/act_mirred.ko
insmod $KERNEL_DIR/kernel/net/sched/cls_fw.ko
insmod $KERNEL_DIR/kernel/net/sched/sch_htb.ko
insmod $KERNEL_DIR/kernel/net/sched/sch_prio.ko
ifconfig imq0 up
fi
fi
# load ebtable filter module
insmod $KERNEL_DIR/kernel/net/bridge/netfilter/ebtables.ko
insmod $KERNEL_DIR/kernel/net/bridge/netfilter/ebtable_filter.ko
insmod $KERNEL_DIR/kernel/net/bridge/netfilter/ebt_ip.ko
if [ "$TCSUPPORT_BRIDGEARP_NOFWD_LAN" != ""  -o  "$TCSUPPORT_CZ_GENERAL" != "" ] ;then
insmod $KERNEL_DIR/kernel/net/bridge/netfilter/ebt_arp.ko
fi
if [ "$TCSUPPORT_IPV6" != "" ] ;then
insmod $KERNEL_DIR/kernel/net/bridge/netfilter/ebt_ip6.ko
fi

if [ "$TCSUPPORT_IGMP_SNOOPING" != "" ] ;then
insmod /lib/modules/igmpsnoop.ko
fi

if [ "$TCSUPPORT_2_6_36_KERNEL" = "" ] ;then
if [ "$TCSUPPORT_MLD_SNOOPING" != "" ] ;then
insmod /lib/modules/mldsnooping.ko
fi
fi

ifconfig lo 127.0.0.1
route add -net 127.0.0.0 netmask 255.255.0.0 lo

ifconfig eth0 0.0.0.0


if [ "$TCSUPPORT_CPU_RT63365" != "" ] || [ "$TCSUPPORT_CPU_RT63368" != "" ] ;then
if [ -f "/proc/tc3162/sys_has_hwnat" ] ;then
if [ "$TCSUPPORT_RA_HWNAT" != "" ] ;then
insmod /lib/modules/hw_nat.ko
fi
fi	
fi

brctl addbr br0
brctl addif br0 eth0

brctl setfd br0 0
brctl stp br0 off

ifconfig eth0 | sed -n '1p' | sed 's/^.*HWaddr /WAN_MAC=/g' >> /etc/mac.conf
ifconfig eth0 | sed -n '1p' | sed 's/^.*HWaddr /LAN_MAC=/g' >> /etc/mac.conf

if [ "$TCSUPPORT_WLAN" != "" ] ;then
echo "TCSUPPORT_WLAN: ifconfig"
i=0
CONFFILE=/etc/Wireless/WLAN_APOn

if [ -f $CONFFILE ] ;then
	chmod 777 $CONFFILE
	. $CONFFILE
	if [ "$TCSUPPORT_WLAN_PERSSID_SWITCH" != "" ] ;then
		case "$APOn" in
			"1" )
				while [ "$i" -lt "$Bssid_num" ];do
				 	case "$i" in
				 	"0" )
						if [ "$ssid0" = "1" ] ;then 
							ifconfig ra$i 0.0.0.0 up
							brctl addif br0 ra$i
						fi
						;;
					"1" )
						if [ "$ssid1" = "1" ] ;then
							ifconfig ra$i 0.0.0.0 up
			                brctl addif br0 ra$i
						fi
						;;
					"2" )
						if [ "$ssid2" = "1" ] ;then
							ifconfig ra$i 0.0.0.0 up
			                brctl addif br0 ra$i
						fi
						;;
					"3" )
						if [ "$ssid3" = "1" ] ;then
							ifconfig ra$i 0.0.0.0 up
			                brctl addif br0 ra$i
						fi
						;;
					esac
					i=`expr $i + 1`
					done
				;;
			"0" )
				while [ "$i" -lt "$Bssid_num" ];do
					ifconfig ra$i 0.0.0.0 up
					brctl addif br0 ra$i
					ifconfig ra$i 0.0.0.0 down
					i=`expr $i + 1`
				done			
				;;
		esac
	else
		while [ "$i" -lt "$Bssid_num" ];do
			case "$APOn" in
				"1" )
					ifconfig ra$i 0.0.0.0 up
					brctl addif br0 ra$i
					;;
				"0" )	
					ifconfig ra$i 0.0.0.0 up
					brctl addif br0 ra$i
					ifconfig ra$i 0.0.0.0 down
					;;
			esac	
		i=`expr $i + 1`
		done
	fi

	if [ "$TCSUPPORT_WLAN_WDS" != "" ] ;then
		echo "TCSUPPORT_WLAN_WDS"
		if [ "$TCSUPPORT_C1_OBM" != "" ] ;then
		case "$WdsEnable" in
			"1"|"2"|"3"|"4" )
				if [ "$Wds0ON" = "1" ] ;then
					ifconfig wds0 0.0.0.0 up
					brctl addif br0 wds0
				fi
				if [ "$Wds1ON" = "1" ] ;then
					ifconfig wds1 0.0.0.0 up
					brctl addif br0 wds1
				fi
				if [ "$Wds2ON" = "1" ] ;then
					ifconfig wds2 0.0.0.0 up
					brctl addif br0 wds2
				fi
				if [ "$Wds3ON" = "1" ] ;then
					ifconfig wds3 0.0.0.0 up
					brctl addif br0 wds3
				fi
				;;
			"0" )
				;;
		esac
		else
		case "$WdsEnable" in
			"1"|"2"|"3"|"4" )
					ifconfig wds0 0.0.0.0 up
					brctl addif br0 wds0
					ifconfig wds1 0.0.0.0 up
					brctl addif br0 wds1
					ifconfig wds2 0.0.0.0 up
					brctl addif br0 wds2
					ifconfig wds3 0.0.0.0 up
					brctl addif br0 wds3
				;;
			"0" )
				;;
		esac
		fi
	fi
	if [ "$TCSUPPORT_FON" != "" ] || [ "$TCSUPPORT_FON_V2" != "" ] ;then
		if [ "$Bssid_num" -ge "2" ] ;then
			brctl delif br0 ra1
			ifconfig ra1 down
		fi
	fi
fi
i=0
CONFFILE=/etc/Wireless/WLAN_APOn_AC

if [ -f $CONFFILE ] ;then
	chmod 777 $CONFFILE
	. $CONFFILE
	if [ "$TCSUPPORT_WLAN_PERSSID_SWITCH" != "" ] ;then
		case "$APOn" in
			"1" )
				while [ "$i" -lt "$Bssid_num" ];do
				 	case "$i" in
				 	"0" )
						if [ "$ssid0" = "1" ] ;then 
							ifconfig rai$i 0.0.0.0 up
							brctl addif br0 rai$i
						fi
						;;
					"1" )
						if [ "$ssid1" = "1" ] ;then
							ifconfig rai$i 0.0.0.0 up
			                brctl addif br0 rai$i
						fi
						;;
					"2" )
						if [ "$ssid2" = "1" ] ;then
							ifconfig rai$i 0.0.0.0 up
			                brctl addif br0 rai$i
						fi
						;;
					"3" )
						if [ "$ssid3" = "1" ] ;then
							ifconfig rai$i 0.0.0.0 up
			                brctl addif br0 rai$i
						fi
						;;
					esac
					i=`expr $i + 1`
					done
				;;
			"0" )
				while [ "$i" -lt "$Bssid_num" ];do
					ifconfig rai$i 0.0.0.0 up
					brctl addif br0 rai$i
					ifconfig rai$i 0.0.0.0 down
					i=`expr $i + 1`
				done			
				;;
		esac
	else
		while [ "$i" -lt "$Bssid_num" ];do
			case "$APOn" in
				"1" )
					ifconfig rai$i 0.0.0.0 up
					brctl addif br0 rai$i
					;;
				"0" )	
					ifconfig rai$i 0.0.0.0 up
					brctl addif br0 rai$i
					ifconfig rai$i 0.0.0.0 down
					;;
			esac	
		i=`expr $i + 1`
		done
	fi
fi
fi

if [ "$TCSUPPORT_DUAL_WLAN_RT5592" != "" ] ;then
ifconfig ra1 0.0.0.0 up
brctl addif br0 ra1
fi	
if [ "$TCSUPPORT_DUAL_WLAN_RT3593" != "" ] ;then
ifconfig ra1 0.0.0.0 up
brctl addif br0 ra1
fi
if [ "$TCSUPPORT_DUAL_WLAN_RT5592_RT3593" != "" ] ;then
ifconfig rai0 0.0.0.0 up
brctl addif br0 rai0
fi

HOSTNAME=`/userfs/bin/tcapi get Snmpd_Entry sysName`
# Set the hostname.
echo $HOSTNAME > /etc/hostname
hostname -F /etc/hostname
rm -rf /etc/hostname

if [ "$TCSUPPORT_CPU_TC3182" != ""  -o "$TCSUPPORT_CPU_RT63165" != "" ] ;then
wan ghs set annex a
wan adsl reset
fi

tcwdog -t 1 /dev/watchdog &
if [ "$TCSUPPORT_DYING_GASP" != "" ] ;then
insmod /lib/modules/dying_gasp.ko
fi

if [ "$TCSUPPORT_RA_MENU" != "" ] ;then
	utelnetd -l /userfs/bin/ra_menu -d 
else
	utelnetd -l /bin/login -d 
fi

if [ "$TCSUPPORT_SSH" != "" ] ;then
echo "SSH"
/userfs/bin/tcapi set ACL_Common sshOption support
else
/userfs/bin/tcapi set ACL_Common sshOption none
fi

if [ "$RA_ETHERMEDIATYPE" != "" ] ;then
echo "Ethernet Media-Type Support"
/userfs/bin/tcapi set Lan_EtherMedia enable support
else
/userfs/bin/tcapi set Lan_EtherMedia enable none
fi

#Web server
/userfs/bin/boa -c /boaroot -d &



if [ "$TCSUPPORT_TC2031" != "" ] ;then
echo "single port"
else
echo "four ports"
/userfs/bin/ethphxcmd eth0 vlanpt disable
if [ "$TCSUPPORT_MT7530_EXTERNAL" != "" ] ;then
/bin/echo 0 > /proc/tc3162/stag_to_vtag
else
/bin/echo 1 > /proc/tc3162/stag_to_vtag
fi
/userfs/bin/ethphxcmd eth0 vlanpt enable
fi

# drop caches
if [ "$TCSUPPORT_MULTISERVICE_ON_WAN" != "" ] ;then
echo 3 > /proc/sys/vm/drop_caches
fi

#. /userfs/startup.sh
/userfs/bin/tcapi set System_Entry start_up 1
/userfs/bin/tcapi commit System_Entry
/userfs/bin/tcapi set System_Entry start_up 0

if [ "$TCSUPPORT_CPU_TC3262" != "" -o "$TCSUPPORT_CPU_TC3182" != ""  -o "$TCSUPPORT_CPU_RT63165" != "" -o "$TCSUPPORT_CPU_RT65168" != "" ] ;then
w rts dbg off
fi

w dmt2 set largeD 2

if [ "$TCSUPPORT_CPU_TC3182" != ""  -o "$TCSUPPORT_CPU_RT63165" != "" -o "$TCSUPPORT_CPU_RT65168" != "" -o "$TCSUPPORT_CPU_RT63368" != "" ] ;then
echo 8 > /proc/irq/12/smp_affinity
taskset -p 0x8 `pidof vtspr`
fi

if [ "$TCSUPPORT_VLAN_TAG" != "" ] ;then
if [ "$TCSUPPORT_VTAG_ALLDEV" != "" ] ;then
/userfs/bin/tcapi set VlanTag_Entry portsNum 4
else
/userfs/bin/tcapi set Info_dot1q wan_8021q 1
fi
fi

echo 1280 > /proc/net/skbmgr_driver_max_skb

if [ "$TCSUPPORT_SDRAM_32M" != "" ] ;then
	echo 4096 > /proc/net/skbmgr_driver_max_skb
if [ "$TCSUPPORT_2_6_36_KERNEL" != "" ] ;then
	echo 4096 > /proc/net/skbmgr_limit
fi
fi
if [ "$TCSUPPORT_SDRAM_64M" != "" ] ;then
	echo 4096 > /proc/net/skbmgr_driver_max_skb
	echo 4096 > /proc/net/skbmgr_limit
fi

if [ "$TCSUPPORT_MEMORY_CONTROL" != "" ] ;then
/bin/echo 1 > /proc/net/auto_clear_cache
/bin/echo 1 > /proc/net/auto_kill_process
/bin/echo 1 > /proc/sys/kernel/panic
/bin/echo 500 > /proc/sys/net/core/netdev_max_backlog
fi
if [ "$TCSUPPORT_TTNET" != "" ] ;then
/bin/echo 600 > /proc/sys/net/netfilter/nf_conntrack_udp_timeout
/bin/echo 600 > /proc/sys/net/netfilter/nf_conntrack_udp_timeout_stream
fi

#network function
if [ "$TCSUPPORT_FTP_USB" != "" ] ;then
	echo "TCSUPPORT_FTP_USB:no need to use inetd!"
	/userfs/bin/p910nd -f /dev/usb/lp0 -b 0 &
else
if [ -f /etc/inetd.conf ]; then
        /userfs/bin/inetd &
fi
fi

#tftp server
/userfs/bin/tftpd &

if [ "$TCSUPPORT_WPA_SUPPLICANT" != "" ] ;then
#seting future date
date 010100002012
#start supplicant control interface 
/userfs/bin/wpa_supplicant -g /var/run/wpa_supplicant &
fi
#

# drop caches
echo 3 > /proc/sys/vm/drop_caches

if [ "$TCSUPPORT_CHT_ARP" != "" ] ;then
/bin/echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore
fi

if [ "$TCSUPPORT_C1_OBM" != "" ] ;then
/bin/echo 1 > /proc/tc3162/port_reverse
if [ "$WIZARD_OI_GUI" != "" ] ;then
/bin/echo "Set WiFi client limit for C1!"
/userfs/bin/iwpriv ra0 set MaxStaNum=16
/userfs/bin/iwpriv ra1 set MaxStaNum=6
fi
fi

if [ "$TCSUPPORT_DUAL_WLAN_RT5592" != "" ] ;then
/userfs/bin/iwpriv ra1 set WirelessMode=10
/userfs/bin/iwpriv ra1 set Channel=52
/userfs/bin/iwpriv ra1 set SSID="RT5592AP"
fi
if [ "$TCSUPPORT_DUAL_WLAN_RT3593" != "" ] ;then
/userfs/bin/iwpriv ra1 set WirelessMode=10
/userfs/bin/iwpriv ra1 set Channel=52
/userfs/bin/iwpriv ra1 set SSID="RT3593AP"
fi
if [ "$TCSUPPORT_DUAL_WLAN_RT5592_RT3593" != "" ] ;then
/userfs/bin/iwpriv rai0 set WirelessMode=10
/userfs/bin/iwpriv rai0 set Channel=157
/userfs/bin/iwpriv rai0 set SSID="Aband_AP"
echo 8 >/proc/irq/24/smp_affinity
echo 4 >/proc/irq/25/smp_affinity
fi	


if [ "$TCSUPPORT_CPU_RT63365" != "" ] ;then
if [ "$TCSUPPORT_CZ_GENERAL" != "" ] ;then
echo "RT63365 cz turn off ether wan webpage!!!"
/userfs/bin/tcapi set WebCustom_Entry haveWan0 No
fi
fi
if [ "$TCSUPPORT_VOIP" != "" ] ;then

echo "MTK DSP support"
COUNTRY=`/userfs/bin/tcapi get VoIPAdvanced_Common VoIPRegion`
echo 3 > /proc/sys/vm/drop_caches
insmod /lib/modules/sys_mod.ko
if [ "$TCSUPPORT_SILICON" != "" ] ;then
insmod /lib/modules/pcm_silicon.ko
else
insmod /lib/modules/pcm.ko
fi
insmod /lib/modules/lec.ko
#insmod /lib/modules/slic3_sep.ko
if [ "$TCSUPPORT_SILICON" != "" ] ;then
insmod /lib/modules/slic3_silicon.ko
else
insmod /lib/modules/slic3.ko
fi
if [ "$TCSUPPORT_SILICON" != "" ] ;then
insmod /lib/modules/fxs3_silicon.ko slic1="si32260" slic2="si32260"
else
if [ "$TCSUPPORT_CPU_RT63368" != "" ] ;then
insmod /lib/modules/fxs3.ko slic1="le89156"
else
if [ "$TCSUPPORT_CPU_MT7510" != "" -o "$TCSUPPORT_CPU_MT7520" != "" ] ;then
insmod /lib/modules/fxs3.ko slic1="zl88601" slic2="zl88601"
else
insmod /lib/modules/fxs3.ko slic1="le89116" slic2="le89316" slic3="le89316"
fi
fi
fi
insmod /lib/modules/ksocket.ko
insmod /lib/modules/ortp.ko
insmod /lib/modules/acodec_x.ko
insmod /lib/modules/foip.ko
insmod /lib/modules/ovdsp.ko
insmod /lib/modules/pcmDump.ko
sleep 1
taskset -p 0x8 `pidof ORTP_TASK`
taskset -p 0x8 `pidof fxs_task`
taskset -p 0x8 `pidof DSPProc`
taskset -p 0x8 `pidof DspDlTask`
taskset -p 0x8 `pidof DspUlTask`

FXSNUM=`cat /proc/fxs/fxsNum`
FXONUM=`cat /proc/fxs/fxoNum`
sleep 2
INFCNUM=`expr $FXSNUM + $FXONUM`
/userfs/bin/tcapi set VoIPSysParam_Common SC_SYS_CFG_MAX_LINE $INFCNUM
/userfs/bin/tcapi set VoIPSysParam_Common SC_SYS_CFG_MAX_ACCT $INFCNUM
STRMNUM=`expr $INFCNUM \* 2`
/userfs/bin/tcapi set VoIPSysParam_Common SC_SYS_CFG_MAX_CALL $STRMNUM
echo "[VOIP] Usage: $INFCNUM acct $STRMNUM"
/userfs/bin/tcapi set VoIPSysParam_Common SlicFXSNum "$FXSNUM"
/userfs/bin/tcapi set VoIPSysParam_Common SlicFXONum "$FXONUM"
if [ "$FXSNUM" = "2" ] ;then
/userfs/bin/tcapi set VoIPBasic_Common VoIPLine2Enable Yes
else
/userfs/bin/tcapi set VoIPBasic_Common VoIPLine2Enable No
fi
/userfs/bin/tcapi set System_Entry start_up 2
/userfs/bin/tcapi commit System_Entry
/userfs/bin/tcapi set System_Entry start_up 0

/userfs/bin/sipclient &
fi
#this must at the end of RCS ----start
if [ "$TCSUPPORT_POWERSAVE_ENABLE" != "" ] ;then
echo 1 > /proc/tc3162/pwm_start
if [ "$TCSUPPORT_WAN_ETHER" != "" ] ;then
echo "wan ether support"
else
/userfs/bin/etherd miiw 4 0 1800
fi
fi
#this must at the end of RCS----end
