#!/bin/sh

. /usr/script/lib_kernel
. /usr/script/lib_xpon
. /usr/script/lib_modules
. /usr/script/lib_xdsl

PROFILE_CFG=/userfs/profile.cfg
if [ -f $PROFILE_CFG ] ; then
    chmod 777 $PROFILE_CFG
    . $PROFILE_CFG
fi

mount -a

if [ "$TCSUPPORT_CT_DBUS" != "" ];then
echo "framework_load"
/usr/script/framework_load.sh
if [ "$TCSUPPORT_CT_JOYME4" != "" ] ;then
/bin/echo 1 > /proc/sys/net/ipv4/conf/all/arp_ignore
fi
fi

/bin/busybox cp -a /usr/etc /tmp

/bin/mkdir -m 0777 -p /tmp/var
if [ "$TCSUPPORT_CUC" != "" ] ;then
/bin/mkdir -m 0777 -p /tmp/run
fi
/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/sim
/bin/mkdir -m 0777 -p /var/tmp
if [ "$TCSUPPORT_CT_MIDWARE" != "" ] ;then
/bin/mkdir -m 0777 -p /var/ct/tmp
fi
if [ "$TCSUPPORT_CT_WLAN_JOYME3" != "" ] ;then
/bin/mkdir -m 0777 -p /var/ctcwifi
fi

if [ "$TCSUPPORT_CT_UBUS" != "" ] ;then
/bin/mkdir -m 0777 -p /tmp/ctcap
/bin/mkdir -m 0777 -p /tmp/ipks

#/bin/busybox cp -a /usr/script/ipks /tmp/ipks
/usr/script/ctcapd_framework_load.sh
fi

taskset 2 /usr/script/netfilter_ko_load.sh &

#start ubusd & cfg_ng service
taskset 2 /usr/script/cfg_ng_start.sh &

if [ "$TCSUPPORT_NP" = "" ] ;then
taskset 4 /userfs/bin/omci &
fi

if [ "$TCSUPPORT_CT_VRWAN" != "" ] || [ "$TCSUPPORT_NPTv6" != "" ] ;then
taskset 2 insmod $KERNEL_DIR/kernel/net/ipv6/netfilter/ip6table_mangle.ko &
fi
if [ "$TCSUPPORT_CMCC" = "" ] ;then
if [ "$TCSUPPORT_CFG_NG_UNION" != "" ] ;then
taskset 2 insmod /lib/modules/attackprotector.ko &
fi
fi

#create reboot_info for dbus after ntpserver sync
if [ "$TCSUPPORT_CT_JOYME2" != "" ] ;then
echo 1 > /proc/sys/vm/panic_on_oom
if [ "$TCSUPPORT_CT_DBUS" != "" ] ;then
taskset 2 /userfs/bin/dbus_apps_info &
fi
fi

#read flash to get bob
xpon_get_7570bob

#if [ "$TCSUPPORT_CT_MAXNET_DPI" != "" ] && [ "$TCSUPPORT_CMCC" = "" ] ;then
#insmod /lib/modules/maxnetdpi.ko
#fi

if [ "$TCSUPPORT_CMCC" != "" ];then
insmod /lib/modules/ethertype_filter.ko
fi

if [ "$TCSUPPORT_CT_DS_LIMIT" != "" ] ;then
insmod /lib/modules/dataspeed_limit.ko
fi

insmod /lib/modules/tcfullcone.ko
insmod /lib/modules/module_sel.ko

modules_copy_led_config

if [ "$TCSUPPORT_NP" = "" ] ;then
if [ "$TCSUPPORT_CT_JOYME2" != "" ] ;then
taskset 2 /userfs/bin/homenas &
fi
fi

#if [ "$TCSUPPORT_SWNAT" != "" ] ;then
#insmod /lib/modules/swnat.ko
#fi

echo 1 > /proc/sys/net/ipv4/ip_forward

echo 1 > /proc/sys/net/ipv4/tcp_syncookies

modules_set_nf_conntrack_max

if [ "$TCSUPPORT_IPV6" != "" ] ;then
echo "TCSUPPORT_IPV6"
#Modify gc_stale_time for IPv6 self test
echo 6000 > /proc/sys/net/ipv6/neigh/default/gc_stale_time

echo 1 >/proc/sys/net/ipv6/conf/all/forwarding
fi

#krammer add for LAN can't continuous ping to WAN when exchenging the routing mode
#bug1126
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout 

echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

if [ "$TCSUPPORT_CT_ACCESSLIMIT" != "" ] ;then
taskset 2 insmod lib/modules/accesslimit.ko &
fi

taskset 2 insmod /lib/modules/tcledctrl.ko
taskset 2 insmod /lib/modules/tccicmd.ko

modules_insmod_secureupgrade

if [ "$TCSUPPORT_I2C" != "" ] ;then
taskset 2 insmod /lib/modules/sif.ko
fi

if [ "$TCSUPPORT_USBDEVICE20" != "" ] ;then
echo "TCSUPPORT_USBDEVICE20"
#usb device
insmod /lib/modules/tc3162_udc20.ko
insmod /lib/modules/g_ether.ko
fi

#if [ "$TCSUPPORT_SOFT_RATELIMIT" != "" ] ;then
#insmod /lib/modules/soft_rate_limit.ko
#fi

if [ "$TCSUPPORT_ASYM_VOD" != "" ] ;then
echo "ASYM VOD"
insmod /lib/modules/asym_vod.ko
fi

if [ "$TCSUPPORT_CT_PON" != "" ] ;then
insmod /lib/modules/nlk_msg.ko
fi


#LED GPIO Settings
CONFFILE=/etc/led.conf
if [ -f $CONFFILE ]; then
	chmod 777 $CONFFILE
	. $CONFFILE
fi
if [ "$LAN" != "" ]; then
	echo $LAN > /proc/tc3162/led_def
fi

/bin/echo 0 > /proc/net/auto_clear_cache
/bin/echo 0 > /proc/net/auto_kill_process
/bin/echo 1 > /proc/sys/kernel/panic
	
modules_proc_skb_limit_config

modules_config_min_free_kbytes

/bin/echo 500 > /proc/sys/net/core/netdev_max_backlog
/bin/echo 3 > /proc/sys/net/netfilter/nf_conntrack_esp_timeout

modules_insmod_crypto

if [ "$TCSUPPORT_FWC_MCST" != "" ] ;then
echo "insmod specific ecnt igmp snooping driver"
insmod /lib/modules/ecnt_igmp.ko
fi

xdsl_insmod_mt7510ptm

modules_insmod_eth_lan_drivers

ifconfig eth0 0.0.0.0

modules_eth1_up

modules_insmod_qdma

modules_insmod_hw_nat

modules_insmod_npu

modules_xsi_wan_up

modules_config_tso_lan_rule

modules_insmod_slm_verify

xpon_config_interface_up

modules_support_bonding

modules_insmod_dmt

if [ "$TCSUPPORT_WAN_ETHER" != "" ] ;then
if [ "$TCSUPPORT_NP_CMCC" != "" ] ;then
taskset 2 ifconfig nas0_0 up &
else
taskset 2 ifconfig nas10 up &
if [ "$TCSUPPORT_MAX_PACKET_2000" != "" ] ;then
taskset 2 ifconfig nas10 mtu 2000 &
fi
fi
fi
if [ "$TCSUPPORT_CT_VLAN_TAG" != "" ] ;then
taskset 2 insmod /lib/modules/vlantag_ct.ko 
fi

if [ "$TCSUPPORT_SMUX" != "" ] ;then
taskset 2 insmod /lib/modules/multiwan.ko &
fi

if [ "$TCSUPPORT_PORTBIND" != "" ] && [ "$TCSUPPORT_CUC_SFU" = "" ] && [ "$TCSUPPORT_SDN_OVS" = "" ] ;then
taskset 2 insmod /lib/modules/tcportbind.ko &
fi

ifconfig eth0 | sed -n '1p' | sed 's/^.*HWaddr /WAN_MAC=/g' | sed 's/[ \t]*$//g' >> /etc/mac.conf
ifconfig eth0 | sed -n '1p' | sed 's/^.*HWaddr /LAN_MAC=/g' | sed 's/[ \t]*$//g' >> /etc/mac.conf

brctl addbr br0
brctl addif br0 eth0
if [ -f "/proc/tc3162/sys_has_2gmac" ] ;then
brctl addif br0 eth1
fi	

modules_add_br_eth1

if [ "$TCSUPPORT_USBDEVICE20" != "" ] ;then
echo "TCSUPPORT_USBDEVICE20: brctl addif br0 usb0"
brctl addif br0 usb0
fi
brctl setfd br0 0
brctl stp br0 off

if [ "$TCSUPPORT_NP" = "" ] ;then
if [ "$TCSUPPORT_WAN_GPON" != "" ] || [ "$TCSUPPORT_WAN_EPON" != "" ] ;then
#pon vlan 
if [ "$TCSUPPORT_PON_VLAN" != "" ] ;then
taskset 2 insmod /lib/modules/ponvlan.ko
fi
#pon igmp snooping
if [ "$TCSUPPORT_XPON_IGMP" != "" ] ;then
taskset 2 insmod /lib/modules/xpon_igmp.ko &
taskset 2 echo bridge nas0_0 > /proc/tc3162/pon_bridge_wanIf &
fi
if [ "$TCSUPPORT_PON_MAC_FILTER" != "" ] ;then
taskset 2 insmod /lib/modules/ponmacfilter.ko &
fi

if [ "$TCSUPPORT_CSC_EEUROPE" != "" ] ||  [ "$TCSUPPORT_MULTICAST_BSP_GENERAL" != "" ];then
echo "mtk xpon multicast"
insmod /lib/modules/mtk_xpon_multicast.ko
fi
fi

taskset 2 /userfs/bin/ponmgr_cfg & 
fi

#if [ "TCSUPPORT_MAP_FILTER" != "" ] ;then
#echo "TCSUPPORT_MAP_FILTER"
#insmod /lib/modules/mapfilter.ko
#fi

insmod /lib/modules/brg_shortcut.ko

modules_config_vlanpt

modules_config_switch_for_map

modules_config_eth_portmap

modules_proc_skb_limit_config_for_wlan

uptime=300;
while [ ! -f "/tmp/call_boot_ok" ] && [ $uptime -gt 0 ]; do
echo "/tmp/call_boot_ok is not exist, left time is $uptime"; 
sleep 1;
uptime=`expr $uptime - 1`;
done;

/userfs/bin/msg call 4097 boot

#USB Backup and Restore
if [ "$TCSUPPORT_CT_USB_BACKUPRESTORE" != "" ] ;then
/userfs/bin/mtd readflash /tmp/var/romfile.cfg~~ 65536 0 romfile
fi

modules_insmod_swqos

if [ "$TCSUPPORT_FWC_TRAFFIC_CLASSIFY" != "" ] || [ "$TCSUPPORT_CMCCV2" != "" ] || [ "$TCSUPPORT_CUC" != "" ] ;then
insmod /lib/modules/traffic_classify.ko
fi

if [ "$TCSUPPORT_CMCCV2" != "" ] ;then
insmod /lib/modules/wlanshare.ko
fi

if [ "$TCSUPPORT_CMCCV2" != "" ] || [ "$TCSUPPORT_CUC" != "" ] ;then
insmod /lib/modules/trafficprocess.ko
fi

kernel_support_qos

if [ "$TCSUPPORT_IGMP_SNOOPING" != "" ] ;then
insmod /lib/modules/igmpsnoop.ko
fi

if [ "$TCSUPPORT_MLD_SNOOPING" != "" ] ;then
insmod /lib/modules/mldsnooping.ko
fi

if [ "$TCSUPPORT_CT_LOOPDETECT" != "" ] ;then
#if [ "$TCSUPPORT_WAN_ETHER" = "" ] ;then
insmod /lib/modules/loopdetect.ko
#fi
fi

if [ "$TCSUPPORT_EPON_DUMMY" != "" ] ;then
insmod /lib/modules/bridgedetect.ko
fi

ifconfig lo 127.0.0.1
route add -net 127.0.0.0 netmask 255.255.0.0 lo

if [ -f "/proc/tc3162/sys_has_2gmac" ] ;then
ifconfig eth1 0.0.0.0
fi	
if [ "$TCSUPPORT_USBDEVICE20" != "" ] ;then
echo "TCSUPPORT_USBDEVICE20: ifconfig usb0 0.0.0.0 up"
ifconfig usb0 0.0.0.0 up
fi



if [ "$TCSUPPORT_SOFT_RATELIMIT" != "" ] ;then
insmod /lib/modules/soft_rate_limit.ko
fi

if [ "$TCSUPPORT_CT_JOYME_BANDWIDTH" != "" ] ;then
insmod /lib/modules/bandwidth.ko
fi

if [ "$TCSUPPORT_LRO_ENABLE" != "" ] ;then
insmod /lib/modules/lro_lan.ko
insmod /lib/modules/lro_wan.ko
echo 1600000 > /proc/sys/net/core/rmem_max
fi

modules_insmod_l2tp_offload

modules_insmod_gre_hw_offload

modules_insmod_vxlan_hw_offload

if [ "$TCSUPPORT_MACDUPDETECT" != "" ] ;then
insmod /lib/modules/macdup_detect.ko
fi

if [ "$TCSUPPORT_VLAN_ACCESS_TRUNK" != "" ] ;then
portbindcmd disable
echo 1 > /sys/class/net/br0/bridge/vlan_filtering
fi

if [ "$TCSUPPORT_CT_URL_FILTER" != "" ] ;then
insmod lib/modules/urlfilter.ko
fi

HOSTNAME=`/userfs/bin/tcapi get Snmpd_Entry sysName`
# Set the hostname.
echo $HOSTNAME > /etc/hostname
hostname -F /etc/hostname
rm -rf /etc/hostname

taskset 2 tcwdog -t 1 /dev/watchdog &

if [ "$TCSUPPORT_CT_NETWORKMANAGESERVICE" != "" ] ;then
echo "TCSUPPORT_CT_NETWORKMANAGESERVICE:no need to start utelnetd up in rcs!"
else
taskset 2 utelnetd -l /bin/login -d 
fi

#Web server
/userfs/bin/boa -c /boaroot -d &

#network function
if [ "$TCSUPPORT_CT_NETWORKMANAGESERVICE" != "" ] ;then
echo "TCSUPPORT_CT_NETWORKMANAGESERVICE:no need to use inetd!"
else
if [ -f /etc/inetd.conf ]; then
        /userfs/bin/inetd &
fi
fi

#tftp server
if [ "$TCSUPPORT_CT" = "" ] ;then
/userfs/bin/tftpd &
fi

if [ "$TCSUPPORT_CT_UBUS" != "" ];then
/usr/script/ctcapd_start.sh
fi

if [ "$TCSUPPORT_CMCCV2" != "" ] ;then
/userfs/bin/dnshost & 
fi

if [ "$TCSUPPORT_CT_E8GUI" != "" ] ;then
/userfs/bin/tcapi set Account_Entry0 Logged 0
/userfs/bin/tcapi set Account_Entry1 Logged 0
/userfs/bin/tcapi set Account_Entry2 Logged 0
fi

#USB Backup and Restore
if [ "$TCSUPPORT_CT_USB_BACKUPRESTORE" != "" ] ;then
sh /usr/script/restore.sh
fi

modules_config_lan_interface_mtu

if [ "$TCSUPPORT_NP" = "" ] ;then
#epon_dummy_detect
if [ "$TCSUPPORT_EPON_DUMMY" != "" ] ;then
/userfs/bin/epon_dummy_detect &
sleep 1
taskset -p 0x1 `pidof epon_dummy_detect`
fi
fi

if [ "$TCSUPPORT_CMCC" = "" ] ;then
if [ "$TCSUPPORT_CT_JOYME2" = "" ] ;then
if [ "$TCSUPPORT_VOIP" != "" ] ;then
/usr/script/voip_load.sh &
fi
fi
fi

if [ "$TCSUPPORT_CUC" != "" ] || [ "$TCSUPPORT_CT_PON_JS" != "" ] ;then
/userfs/bin/hw_nat -U 60 60 60 60
fi

if [ "$TCSUPPORT_NP_CMCC" != "" ] ;then
/userfs/bin/hw_nat -U 300 300 300 300
fi

if [ "$TCSUPPORT_GPON_ATTACK_ENHANCE" != "" ] ;then
echo 1 64 128 100 > /proc/qdma/protect_mode
echo 1 128 100 > /proc/tc3162/protect_mode
fi

if [ "$TCSUPPORT_CFG_NG_UNION" != "" ] ;then
echo restoresw 1 >/proc/tc3162/vlan_tag_dbg 
fi

if [ "$TCSUPPORT_CT_DS_LIMIT" != "" ] ;then
if [ "$TCSUPPORT_CT_JOYME_BANDWIDTH" != "" ] ;then
/userfs/bin/tcapi set DataSpeedLimit_Entry isBOOT 1
fi
/userfs/bin/tcapi commit DataSpeedLimit
fi

if [ "$TCSUPPORT_GPON_ATTACK_ENHANCE" != "" ] ;then
/bin/echo 1 64 128 100 > /proc/qdma/protect_mode
/bin/echo 1 128 100 > /proc/tc3162/protect_mode
fi

if [ "$TCSUPPORT_FWC_MCST" != "" ] ;then
/userfs/bin/hw_nat -V1
fi

if [ "$TCSUPPORT_BNDSTRG_WLAN" != "" ] ;then
/etc/Wireless/RT2860AP/WLAN_bndstrg_exec.sh
/etc/Wireless/RT2860AP_AC/WLAN_bndstrg_exec.sh
fi

if [ "$TCSUPPORT_CMCCV2" != "" ] ;then
/userfs/bin/tcapi set System_Entry devicereboot 1
/userfs/bin/tcapi commit System_Entry
/userfs/bin/tcapi set System_Entry devicereboot 0
fi

modules_insmod_dying_gasp

modules_irqCpuBind_and_sw_rps_config
if [ "$TCSUPPORT_CT_DBUS" != "" ] || [ "$TCSUPPORT_CMCCV2" != "" ] ;then
insmod /lib/modules/speedtest.ko
fi

if [ "$TCSUPPORT_CT_DBUS" != "" ];then
insmod /lib/modules/info_utility.ko
/userfs/bin/trafficvpninfo &
/userfs/bin/process_monitor &
/userfs/bin/cputemp socket &
fi
if [ "$TCSUPPORT_CT_UBUS" != "" ];then
echo "start cpu temp"
/userfs/bin/cputemp socket &
fi
if [ "$TCSUPPORT_VLAN_ACCESS_TRUNK" != "" ];then
/usr/bin/portbindcmd disable
echo 1 > /sys/class/net/br0/bridge/vlan_filtering
fi

if [ "$TCSUPPORT_CT_UBUS" != "" ];then
if [ "$TCSUPPORT_CT_JOYME_BANDWIDTH" != "" ] ;then
taskset 2 /userfs/bin/bandwidth & 
fi
fi

modules_insmod_iptv_udpxy

if [ "$TCSUPPORT_ECNT_MAP" != "" ] ;then
/userfs/bin/ethphxcmd arl aging 1 30
fi

#detect power saving mode
if [ -f /tmp/low_power ] ; then
	/userfs/bin/pwctlcmd lowpwr 3
fi

#this must at the end of RCS----end
